### ISSUE TITLE
Upload failed, status code: SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by emtiazzahid** [sitevision/sitevision-apps#109]
After running dev its showing that error. here are the log

```
λ npm run dev

> sitevision-app@0.0.1 dev
> sitevision-scripts dev

[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src\**\*
[nodemon] watching extensions: js,html,css,less,json
[nodemon] starting `node C:\laragon\www\sitevision-app\node_modules\@sitevision\sitevision-scripts\bin\sitevision-scripts.js build force-deploy`
Successfully compiled 3 files with Babel (724ms).
Compression successful
Upload failed, status code: SyntaxError: Unexpected token < in JSON at position 0
[nodemon] clean exit - waiting for changes before restart
```

node -v : v18.12.1
npm -v: 9.8.0

can anyone help please

**Comment by magloven** [comment]
"Unexpected token < in JSON at position 0" typically indicates that the response is in html format. The first that comes to mind is that the error page of the site might be returned. This could be the case for a bad request (bad domain, bad data) or a request that lacks permission to perform what the endpoint is supposed to do.

- Ensure that you have created the actual addon (npm run create-addon) before you use dev to auto-deploy app changes.
- Check the credentials (user should have permission to WRITE and MANAGE_ADDONS).
- Also check other environment settings (proper domain, proper site name, proper addon name etc)

**Comment by emtiazzahid** [comment]
Thanks for your reply.
I think its related with dev_properties data I have
here are the sample format I using. 
note: I have changed the characters for safety.
```
{
  "domain": "use-opreno.sitevision-cloud.se",
  "siteName": "my site",
  "addonName": "mysiteaddon",
  "username": "test@test.no",
  "password": "eAl-Gfpse1GTFL"
}
```
and after I changed the username for test purpose the error is changed to 
`Upload failed, status code: SyntaxError: Unexpected end of JSON input`

npm run create-addon mysiteaddon also gives same error
```Addon creation failed:, SyntaxError: Unexpected end of JSON input```
