### ISSUE TITLE
Möjlighet att använda Vue.js i stället för React

### ISSUE THREAD

**Issue by oskarannas** [sitevision/sitevision-apps#117]
Finns det stöd i webapps 2 för att byta ut React mot Vue?

Och i så fall, finns det någon dokumentation kring detta? Alt. någon exempelkod?

**Comment by albinohrn** [comment]
Tjena!

I WebApps 2 finns det alla möjligheter att byta ut React mot Vue. För clientside-rendering kan man använda vilket ramverk man vill. För serverside-rendering rekommenderar vi React eftersom det är det som vi använder själva, testar och vet fungerar. Jag vet dock att andra använder andra ramverk för server-rendering, t ex Svelte, Vue är jag osäker på om någon använder.

För att det ska fungera med @sitevision/create-sitevision-app är skulle det dock behöva till några förändringar likt dom som efterfrågas i #116. Men det är fullt möjligt att sätta upp sin egen webpack/rollup-config och supporta Vue på det sättet.

Hoppas att det svarar på dig fråga!
