### ISSUE TITLE
Lägg med maxUploadSizeInMB i manifest.json

### ISSUE THREAD

**Issue by oskarakerlund-consid** [sitevision/sitevision-apps#126]
Då Sitevision nu [rekommenderar](https://developer.sitevision.se/archives/developer-news/developer-news/2024-02-01-specify-expected-file-size-in-the-manifest) att alltid ha med `maxUploadSizeInMB` i `manifest.json`, vore det bra om det lades in som default under [template](https://github.com/sitevision/sitevision-apps/tree/main/packages/sitevision-scripts/template).

Värdet bör kunna sättas till 0 som standard då de flesta appar säkert inte tar emot filer i anropet.

Annars tror jag det blir svårt att få rutin på att manuellt lägga in detta i alla appar vi bygger. En eventuell negativ konsekvens är att värdet 0 inte har stöd i äldre installationer on-prem, men jag skulle säga att fördelarna väger över den nackdelen.

**Comment by robinlagren** [comment]
Det är på gång och kommer lösas inom kort. Tack för input 👍
