### ISSUE TITLE
Problem med chalk efter senaste uppdateringen

### ISSUE THREAD

**Issue by JWahlander** [sitevision/sitevision-apps#54]
Det fungerar inte att köra create-sitevision-app längre efter senaste uppdateringen av package.json där chalk har uppdaterats till version 5.0.1.
Man får ett felmeddelande som antyder att man inte längre kan använda "require" vilket används i createSitevisionApp.js.

```
C:\Users\joaki\AppData\Local\npm-cache\_npx\1a7a99daebf6da00\node_modules\@sitevision\create-sitevision-app\createSitevisionApp.js:1
const chalk = require('chalk');
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\joaki\AppData\Local\npm-cache\_npx\1a7a99daebf6da00\node_modules\chalk\source\index.js from C:\Users\joaki\AppData\Local\npm-cache\_npx\1a7a99daebf6da00\node_modules\@sitevision\create-sitevision-app\createSitevisionApp.js not supported.
Instead change the require of index.js in C:\Users\joaki\AppData\Local\npm-cache\_npx\1a7a99daebf6da00\node_modules\@sitevision\create-sitevision-app\createSitevisionApp.js to a dynamic import() which is available in all CommonJS modules.
```

**Comment by albinohrn** [comment]
Ber om ursäkt för det. Det finns nya versioner av berörda paket nu publicerade. Tack för rapport!

**Comment by JWahlander** [comment]
> Ber om ursäkt för det. Det finns nya versioner av berörda paket nu publicerade. Tack för rapport!

Ingen fara, tack för snabb fix. 👍 
Jag hann ju knappt hämta en kopp kaffe! :)
