### ISSUE TITLE
Suggestion: option for react-less client side

### ISSUE THREAD

**Issue by oskarakerlund-consid** [sitevision/sitevision-apps#66]
Use case: building WebApp2 which only does server-side rendering but without the need for React in the browser.

Currently, the boilerplate code will instruct Sitevision to include React 17 on page load even if I don't need any interactivitiy on the client side. I would like an option / shortcut to build a WebApp2 without React on the client side. 

This is how I can solve it manually:

- index.js: replace `res.agnosticRender(renderToString(` with `res.send(renderToStaticMarkup(`
- main.js: delete all contents, leave file blank
- mainfest.json: remove "react" from "requiredLibs"

I would prefer to have an option such as `npx @sitevision/create-sitevision-app my-new-app --no-client-react` or even better, a question in the installation wizard.

**Comment by albinohrn** [comment]
Thanks for your suggestion, we'll look in to this! :)
