### ISSUE TITLE
Variables are not redeclared in looping scopes when creating an app with TypeScript

### ISSUE THREAD

**Issue by Wiktry** [sitevision/sitevision-apps#81]
### Description

When declaring a `const` variable inside a looped scope that variable will not update during loops beyond the first. This issue does not occur when using normal JavaScript.

### Example code

```javascript
for (let i = 0; i < 10; i++) {
    const test = i;
    logUtil.info(JSON.stringify(test));
}
```

This code should print 0 to 9, but currently prints 10 zeros.

### Using

Sitevision 2022.11.1.1
sitevision api: 2023.2.1
sitevision-scripts: 3.1.5

### Additional

The same issue occurs when creating a script module directly on a Sitevision page using the following code:

```javascript
for (let i = 0; i < 10; i++) {
   const test = i;
   out.println(test);
}
```

**Comment by albinohrn** [comment]
Good catch!

This is due to incompatibilities in the Rhino scripting engine. You can fix this by updating your tsconfig.json to 

```json
{
  "compilerOptions": {
    "target": "ES5"
    ...
  }
}
```

I will update the provided tsconfig to address this...

**Comment by Wiktry** [comment]
Thanks for a quick answer. I'm guessing [Issue 83](https://github.com/sitevision/sitevision-apps/issues/83) will have the same solution, then. But I'm leaving it up for posterity.

**Comment by albinohrn** [comment]
Yes! #83 will be solved by the same fix! 

Thanks you for your reports!
