### ISSUE TITLE
Variables are not block scoped in TypeScript

### ISSUE THREAD

**Issue by Wiktry** [sitevision/sitevision-apps#83]
### Description

When declaring a `const` variable inside a child scope that variable will persist throughout the parent's scope.

### Example code

```javascript
try {
    const test = 1;
} catch (e) {
    console.log(e);
}

try {
    const test = 1;
} catch (e) {
    console.log(e);
}
```

Since const is a scoped variable, this should not produce an error. However, it currently produces an "EvaluatorException: TypeError: redeclaration of const" error. Using `let` results in the same error.

### Why is this an issue?

The minifier transpiles down all variables to single letters, starting over from the top whenever a new scope is created. Thus all scopes will have all the same variables.

### Work around

This issue is limited to scopes within a function scope. Creating a new function for each scope will circumnavigate it.

### Using

Sitevision 2022.11.1.1
sitevision api: 2023.2.1
sitevision-scripts: 3.1.5

### Additional

The same issue occurs when creating a script module directly on a Sitevision page.

**Comment by albinohrn** [comment]
Fixed by #82
