### ISSUE TITLE
Fel typ på sträng för Properties.get

### ISSUE THREAD

**Issue by JWahlander** [sitevision/sitevision-apps#86]
Hej,

Följande fel ges när man skickar in en sträng i get-metoden för Properites.
"Argument of type 'string' is not assignable to parameter of type 'String | string[]'"

T ex:  `const displyName = properties.get(node, 'displayName');`

![image](https://user-images.githubusercontent.com/53211927/224332083-9794cc7b-0a79-48f2-8469-79ee494c4392.png)

Borde det inte vara `string | string[]` som typ?

**Comment by albinohrn** [comment]
Tack för rapport!

Det ska vara en varArgs, fixat i #85. Om du vill kan du hoppa på den nya versionen genom att installera  @sitevision/api@next (`npm install @sitevision/api@next`). Släpps skarpt i samband med nästa sv-version.

**Comment by JWahlander** [comment]
Tack! @albinohrn! Den nya releasen fixade dessutom några andra fel som jag tänkt rapportera! Snyggt! :)
