### ISSUE TITLE
TypeScript-fel: AppData.get och GlobalAppData.get tar bara ett argument

### ISSUE THREAD

**Issue by JWahlander** [sitevision/sitevision-apps#87]
Hej,

get-metoden för AppData och GlobalData är bara typad att ta ett argument, key av typen string. Det går alltså inte att skicka med en eller flera JCR Node-properties.

![image](https://user-images.githubusercontent.com/53211927/224348273-d21c8ecd-50b0-4381-82ab-609d6496804e.png)

**Comment by albinohrn** [comment]
Tack för rapport!

Har uppdaterat `@next` med fix.
