### ISSUE TITLE
TypeScript fel för Privileged (RestApp)

### ISSUE THREAD

**Issue by DalmasN** [sitevision/sitevision-apps#91]
Har en restapp som är byggd med typescript och där jag försöker använda privileged.
Får nedanstående error när jag gör ett anrop mot restappen. Privilegierat läge är aktiverat och en tjänsteanvändare har tilldelats.
Fick för övrigt också samma typ av fel när jag försökte använda "doPrivilegedAction" metoden.

500: error
{
   "success": false,
   "type": "unknown",
   "description": "Unknown error occurred",
   "message": "EcmaError: TypeError: Cannot call method \"isConfigured\" of null (#48)"
}
 
 
Kod: 
`import router from "@sitevision/api/common/router";
import privileged from '@sitevision/api/server/privileged';
router.post('/sync', (req, res) => {
  privileged.doPrivilegedAction(() => {
    synchronize();
  });
});
`

**Comment by robinlagren** [comment]
Hej,

Har du lagt till  `"requirePrivileged": true` i appens [manifest](https://developer.sitevision.se/docs/rest-api/restapps/require/privileged#Manifest)? (Borde även tydliggöras vid konfiguration av serviceanvändare i gränssnittet)

**Comment by DalmasN** [comment]
Hej,

Jag får be om ursäkt, hade glömt att lägga till det i manifestet.
Nu funkar allt som det ska. Då stänger jag ärendet.
