### ISSUE TITLE
Promises in RestApps

### ISSUE THREAD

**Issue by filiphuhta** [sitevision/sitevision-apps#92]
Hej!

Jag funderar om det finns möjlighet att använda [Promise()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) för att kunna göra asynkrona funktioner i **RestAppar**?

Jag har testat lägga in det på flera olika sätt men inte fått det att fungera. Ser att det finns i **node_modules** men det går inte att använda sig av i apparna. Skulle underlätta för oss utvecklare enormt då kunder kräver en synkning av något slag som kör på serversidan.

Absolut bäst vore det ju såklart om det skulle stödjas `async` & `await`. Men det ser jag inte att **Rhino** har stöd för.

**Comment by albinohrn** [comment]
Tjena!

Den version av Rhino vi använder i dagsläget stödjer inte Promises. Om du har något i node_modules som ska hjälpa detta så antar jag att det är någon typ av polyfill? Dom brukar vara beroende av `setTimeout` och det saknas också i versionen av Rhino vi använder.

Vi tittar på att uppgradera men den senaste versionen innehåller Breaking changes som vi måste hantera för att kunna uppgradera.

**Comment by filiphuhta** [comment]
Hej!

Då var det som jag tänkte att det är omöjligt med just den Rhino versionen som används. Vad bra att ni tittar på att uppgradera detta för det skulle verkligen behövas. :) @albinohrn
