### ISSUE TITLE
npm run zip is no longer included

### ISSUE THREAD

**Issue by NickLindstromB3** [sitevision/sitevision-apps#96]
I've got a error message when i tried to run "npm run deploy-prod" that I should use "npm run zip", but that is no longer included.

I'm guessing that the error message should be changed to match the current situation.

![image](https://user-images.githubusercontent.com/126068231/236794839-e0eea0b3-0d9e-4a8a-9d9e-f308c69d6eda.png)

**Comment by albinohrn** [comment]
Thanks for reporting! 

The zip stage is now included when running `npm run build`.
