### ISSUE TITLE
throw new UndefinedParserError(`No parser could be inferred for file: ${rawOptions.filepath}`);

### ISSUE THREAD

**Issue by AndersenMattias** [sitevision/sitevision-apps#99]
Jag stöter på problem när jag försöker skapa upp en ny WebApp.. Jag har satt disable på min Prettier som ett försök men det fungerar fortfarande inte. Ni har lagt in prettier i er senaste PR om jag inte såg fel. 

Tips för att kunna komma runt detta problem? 👍 

![Screenshot 2023-05-29 at 11 07 57](https://github.com/sitevision/sitevision-apps/assets/64038954/74b8c8ce-2a45-4d7b-bfad-25b61085630f)
![Screenshot 2023-05-29 at 11 13 07](https://github.com/sitevision/sitevision-apps/assets/64038954/0fb75b23-10c8-4129-a281-9510975deee7)
![Screenshot 2023-05-29 at 11 21 40](https://github.com/sitevision/sitevision-apps/assets/64038954/2e16cc93-3358-46d2-9b1d-7ae1d9e16e64)

**Comment by AndersenMattias** [comment]
@albinohrn @robinlagren

**Comment by albinohrn** [comment]
Det ser ut som att det har gått fel när du skapar appen? index.tsx.template borde inte finnas kvar efter skapande.

Får du några fel när du skapar?

**Comment by AndersenMattias** [comment]
@albinohrn 

Problemet låg så klart hos mig.. Efter bollande lokaliserad vi att det var för att jag använde . på min mapp (projektets namn). Bra lärdom att inte ha med punkt och köra med bindestreck i stället :D 

if (outputPath.includes('.')) ..

**Comment by AndersenMattias** [comment]
Kanske kan vara värt att fundera på att ha en fix för det ifall att?

**Comment by albinohrn** [comment]
Japp, vi borde stoppa om namnet innehåller "konstiga" tecken.

Tack för rapport!
